config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    sessions:'users/sessions',
    registrations: 'users/registrations'
  }
  get 'welcome/index'
  resources :comments
  resources :galleries

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  belongs_to :users
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: %i[ show edit update destroy ]

  #usuario normal: user
  before_action only: [:index, :show] do
    authorize_request(["user","admin"])
  end
  #usuario administrador
  before_action only: [:new, :edit, :create, :update, :destroy] do
    authorize_request(["admin"])
  end

  # GET /galleries or /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1 or /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries or /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to gallery_url(@gallery), notice: "Gallery was successfully created." }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1 or /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to gallery_url(@gallery), notice: "Gallery was successfully updated." }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1 or /galleries/1.json
  def destroy
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url, notice: "Gallery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gallery_params
      params.require(:gallery).permit(:image, :description, :users_id)
    end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_form.html.erb
<%= form_with(model: gallery) do |form| %>
  <% if gallery.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
        <% gallery.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :users_id, style: "display: block" %>
    <%= form.text_field :users_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/galleries/_gallery.html.erb
<div id="<%= dom_id gallery %>">
  <p>
    <strong>Image:</strong>
    <%= gallery.image %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= gallery.description %>
  </p>

  <p>
    <strong>Users:</strong>
    <%= gallery.users_id %>
  </p>

</div>

app/views/galleries/edit.html.erb
<h1>Editing gallery</h1>

<%= render "form", gallery: @gallery %>

<br>

<div>
  <%= link_to "Show this gallery", @gallery %> |
  <%= link_to "Back to galleries", galleries_path %>
</div>

app/views/galleries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Galleries</h1>

<div id="galleries">
  <% @galleries.each do |gallery| %>
    <%= render gallery %>
    <p>
      <%= link_to "Show this gallery", gallery %>
    </p>
  <% end %>
</div>

<%= link_to "New gallery", new_gallery_path %>

app/views/galleries/new.html.erb
<h1>New gallery</h1>

<%= render "form", gallery: @gallery %>

<br>

<div>
  <%= link_to "Back to galleries", galleries_path %>
</div>

app/views/galleries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @gallery %>

<div>
  <%= link_to "Edit this gallery", edit_gallery_path(@gallery) %> |
  <%= link_to "Back to galleries", galleries_path %>

  <%= button_to "Destroy this gallery", @gallery, method: :delete %>
</div>